class users::system {
  user { 'adm':
    ensure           => 'present',
    comment          => 'adm',
    gid              => '4',
    groups           => ['sys', 'adm'],
    home             => '/var/adm',
    password         => '*',
    password_max_age => '99999',
    password_min_age => '0',
    shell            => '/sbin/nologin',
    uid              => '3',
  }
  user { 'avahi':
    ensure           => 'present',
    comment          => 'Avahi daemon',
    gid              => '70',
    home             => '/',
    password         => '!!',
    password_max_age => '99999',
    password_min_age => '0',
    shell            => '/sbin/nologin',
    uid              => '70',
  }
  user { 'avahi-autoipd':
    ensure           => 'present',
    comment          => 'avahi-autoipd',
    gid              => '101',
    home             => '/var/lib/avahi-autoipd',
    password         => '!!',
    password_max_age => '99999',
    password_min_age => '0',
    shell            => '/sbin/nologin',
    uid              => '100',
  }
  user { 'bin':
    ensure           => 'present',
    comment          => 'bin',
    gid              => '1',
    groups           => ['bin', 'daemon', 'sys'],
    home             => '/bin',
    password         => '*',
    password_max_age => '99999',
    password_min_age => '0',
    shell            => '/sbin/nologin',
    uid              => '1',
  }
  user { 'daemon':
    ensure           => 'present',
    comment          => 'daemon',
    gid              => '2',
    groups           => ['bin', 'daemon', 'adm', 'lp'],
    home             => '/sbin',
    password         => '*',
    password_max_age => '99999',
    password_min_age => '0',
    shell            => '/sbin/nologin',
    uid              => '2',
  }
  user { 'dbus':
    ensure           => 'present',
    comment          => 'System message bus',
    gid              => '81',
    home             => '/',
    password         => '!!',
    password_max_age => '99999',
    password_min_age => '0',
    shell            => '/sbin/nologin',
    uid              => '81',
  }
  user { 'ftp':
    ensure           => 'present',
    comment          => 'FTP User',
    gid              => '50',
    home             => '/var/ftp',
    password         => '*',
    password_max_age => '99999',
    password_min_age => '0',
    shell            => '/sbin/nologin',
    uid              => '14',
  }
  user { 'games':
    ensure           => 'present',
    comment          => 'games',
    gid              => '100',
    home             => '/usr/games',
    password         => '*',
    password_max_age => '99999',
    password_min_age => '0',
    shell            => '/sbin/nologin',
    uid              => '12',
  }
  user { 'gopher':
    ensure           => 'present',
    comment          => 'gopher',
    gid              => '30',
    home             => '/var/gopher',
    password         => '*',
    password_max_age => '99999',
    password_min_age => '0',
    shell            => '/sbin/nologin',
    uid              => '13',
  }
  user { 'haldaemon':
    ensure           => 'present',
    comment          => 'HAL daemon',
    gid              => '68',
    home             => '/',
    password         => '!!',
    password_max_age => '99999',
    password_min_age => '0',
    shell            => '/sbin/nologin',
    uid              => '68',
  }
  user { 'halt':
    ensure           => 'present',
    comment          => 'halt',
    gid              => '0',
    home             => '/sbin',
    password         => '*',
    password_max_age => '99999',
    password_min_age => '0',
    shell            => '/sbin/halt',
    uid              => '7',
  }
  user { 'lp':
    ensure           => 'present',
    comment          => 'lp',
    gid              => '7',
    groups           => ['lp'],
    home             => '/var/spool/lpd',
    password         => '*',
    password_max_age => '99999',
    password_min_age => '0',
    shell            => '/sbin/nologin',
    uid              => '4',
  }
  user { 'mail':
    ensure           => 'present',
    comment          => 'mail',
    gid              => '12',
    groups           => ['mail'],
    home             => '/var/spool/mail',
    password         => '*',
    password_max_age => '99999',
    password_min_age => '0',
    shell            => '/sbin/nologin',
    uid              => '8',
  }
  user { 'mailnull':
    ensure           => 'present',
    gid              => '47',
    home             => '/var/spool/mqueue',
    password         => '!!',
    password_max_age => '99999',
    password_min_age => '0',
    shell            => '/sbin/nologin',
    uid              => '47',
  }
  user { 'news':
    ensure           => 'present',
    comment          => 'news',
    gid              => '13',
    groups           => ['news'],
    home             => '/etc/news',
    password         => '*',
    password_max_age => '99999',
    password_min_age => '0',
    uid              => '9',
  }
  user { 'nfsnobody':
    ensure           => 'present',
    comment          => 'Anonymous NFS User',
    gid              => '65534',
    home             => '/var/lib/nfs',
    password         => '!!',
    password_max_age => '99999',
    password_min_age => '0',
    shell            => '/sbin/nologin',
    uid              => '65534',
  }
  user { 'nobody':
    ensure           => 'present',
    comment          => 'Nobody',
    gid              => '99',
    home             => '/',
    password         => '*',
    password_max_age => '99999',
    password_min_age => '0',
    shell            => '/sbin/nologin',
    uid              => '99',
  }
  user { 'nscd':
    ensure           => 'present',
    comment          => 'NSCD Daemon',
    gid              => '28',
    home             => '/',
    password         => '!!',
    password_max_age => '99999',
    password_min_age => '0',
    shell            => '/sbin/nologin',
    uid              => '28',
  }
  user { 'ntp':
    ensure           => 'present',
    gid              => '38',
    home             => '/etc/ntp',
    password         => '!!',
    password_max_age => '-1',
    password_min_age => '-1',
    shell            => '/sbin/nologin',
    uid              => '38',
  }
  user { 'operator':
    ensure           => 'present',
    comment          => 'operator',
    gid              => '0',
    home             => '/root',
    password         => '*',
    password_max_age => '99999',
    password_min_age => '0',
    shell            => '/sbin/nologin',
    uid              => '11',
  }
  user { 'pcap':
    ensure           => 'present',
    gid              => '77',
    home             => '/var/arpwatch',
    password         => '!!',
    password_max_age => '99999',
    password_min_age => '0',
    shell            => '/sbin/nologin',
    uid              => '77',
  }
  user { 'postfix':
    ensure           => 'present',
    gid              => '89',
    groups           => ['mail'],
    home             => '/var/spool/postfix',
    password         => '!!',
    password_max_age => '-1',
    password_min_age => '-1',
    shell            => '/sbin/nologin',
    uid              => '89',
  }
  user { 'puppet':
    ensure           => 'present',
    gid              => '500',
    home             => '/home/puppet',
    password         => '!!',
    password_max_age => '99999',
    password_min_age => '0',
    shell            => '/bin/bash',
    uid              => '500',
  }
  user { 'root':
    ensure           => 'present',
    comment          => 'root',
    gid              => '0',
    groups           => ['root', 'bin', 'daemon', 'sys', 'adm', 'disk', 'wheel'],
    home             => '/root',
    password         => '$6$/cfkLEL3$dly9ZLI/4vPa1T7Xaib5eM2a6etbZjRV1.21E5I/WyjSNN/jiGdLh22FVyrFjj0uNu7hoGpw9.yPt978wKYYE/',
    password_max_age => '99999',
    password_min_age => '0',
    shell            => '/bin/bash',
    uid              => '0',
  }
  user { 'rpc':
    ensure           => 'present',
    comment          => 'Portmapper RPC user',
    gid              => '32',
    home             => '/',
    password         => '!!',
    password_max_age => '99999',
    password_min_age => '0',
    shell            => '/sbin/nologin',
    uid              => '32',
  }
  user { 'rpcuser':
    ensure           => 'present',
    comment          => 'RPC Service User',
    gid              => '29',
    home             => '/var/lib/nfs',
    password         => '!!',
    password_max_age => '99999',
    password_min_age => '0',
    shell            => '/sbin/nologin',
    uid              => '29',
  }
  user { 'shutdown':
    ensure           => 'present',
    comment          => 'shutdown',
    gid              => '0',
    home             => '/sbin',
    password         => '*',
    password_max_age => '99999',
    password_min_age => '0',
    shell            => '/sbin/shutdown',
    uid              => '6',
  }
  user { 'smmsp':
    ensure           => 'present',
    gid              => '51',
    home             => '/var/spool/mqueue',
    password         => '!!',
    password_max_age => '99999',
    password_min_age => '0',
    shell            => '/sbin/nologin',
    uid              => '51',
  }
  user { 'sshd':
    ensure           => 'present',
    comment          => 'Privilege-separated SSH',
    gid              => '74',
    home             => '/var/empty/sshd',
    password         => '!!',
    password_max_age => '99999',
    password_min_age => '0',
    shell            => '/sbin/nologin',
    uid              => '74',
  }
  user { 'sync':
    ensure           => 'present',
    comment          => 'sync',
    gid              => '0',
    home             => '/sbin',
    password         => '*',
    password_max_age => '99999',
    password_min_age => '0',
    shell            => '/bin/sync',
    uid              => '5',
  }
  user { 'uucp':
    ensure           => 'present',
    comment          => 'uucp',
    gid              => '14',
    groups           => ['uucp'],
    home             => '/var/spool/uucp',
    password         => '*',
    password_max_age => '99999',
    password_min_age => '0',
    shell            => '/sbin/nologin',
    uid              => '10',
  }
  user { 'vcsa':
    ensure           => 'present',
    comment          => 'virtual console memory owner',
    gid              => '69',
    home             => '/dev',
    password         => '!!',
    password_max_age => '99999',
    password_min_age => '0',
    shell            => '/sbin/nologin',
    uid              => '69',
  }
}
