#!/bin/bash

###################
#
# Totsy development database restore script
# Copies raw database files from a special rsync location to locally.
#
###################

# backup config data
mysqldump -u root magento core_config_data > /tmp/core_config_data.sql

# shutdown mysql server (if it's running)
service mysql status
if [ $? -eq 0 ]
then
    service mysql stop
fi;

# delete existing mysql data
rm -rf /var/lib/mysql/*

# copy mysql data from remote data store
rsync -avP 10.68.18.98::stagingdata /var/lib/mysql/
if [ $? -ne 0 ]
then
    echo "Failed copying mysql data from remote server!"
    exit
fi;

chown -R mysql:mysql /var/lib/mysql/

# restart mysql server
service mysql start

# restore config data
mysql -u root magento < /tmp/core_config_data.sql

